In [2]:
# Importing the required libraries
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
# Reading the csv file and putting it into 'df' object.
df = pd.read_csv("M:\Imarticus\python project\crop-varietal-identification-with-scio\Barley.data.csv")
df.head()

,Predictor,740,741,742,743,744,745,746,747,748,...,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070
0,HB-52,1.499853,1.500665,1.501564,1.502536,1.503537,1.504548,1.505588,1.506689,1.507828,...,1.636411,1.637350,1.636452,1.634370,1.632287,1.630265,1.630722,1.633166,1.636204,1.637872
1,HB-52,1.530877,1.531669,1.532524,1.533419,1.534308,1.535169,1.536024,1.536916,1.537830,...,1.643299,1.644222,1.643302,1.641195,1.639088,1.637046,1.637493,1.639938,1.642981,1.644649
2,HB-52,1.607175,1.608642,1.610044,1.611357,1.612540,1.613585,1.614534,1.615456,1.616359,...,1.703343,1.704291,1.703329,1.701137,1.698946,1.696822,1.697278,1.699806,1.702953,1.704677
3,HB-52,1.677333,1.678098,1.678930,1.679809,1.680688,1.681539,1.682384,1.683260,1.684145,...,1.755067,1.756013,1.754996,1.752716,1.750441,1.748238,1.748696,1.751290,1.754525,1.756294
4,HB-52,1.507830,1.509293,1.510683,1.511977,1.513145,1.514180,1.515125,1.516049,1.516964,...,1.641968,1.642877,1.641946,1.639829,1.637714,1.635664,1.636101,1.638535,1.641567,1.643227

In [5]:
#collecting indepedent variables in X
X = df.iloc[:,1:332]
X_col = X.columns
X.head()

,740,741,742,743,744,745,746,747,748,749,...,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070
0,1.499853,1.500665,1.501564,1.502536,1.503537,1.504548,1.505588,1.506689,1.507828,1.508937,...,1.636411,1.637350,1.636452,1.634370,1.632287,1.630265,1.630722,1.633166,1.636204,1.637872
1,1.530877,1.531669,1.532524,1.533419,1.534308,1.535169,1.536024,1.536916,1.537830,1.538712,...,1.643299,1.644222,1.643302,1.641195,1.639088,1.637046,1.637493,1.639938,1.642981,1.644649
2,1.607175,1.608642,1.610044,1.611357,1.612540,1.613585,1.614534,1.615456,1.616359,1.617205,...,1.703343,1.704291,1.703329,1.701137,1.698946,1.696822,1.697278,1.699806,1.702953,1.704677
3,1.677333,1.678098,1.678930,1.679809,1.680688,1.681539,1.682384,1.683260,1.684145,1.684969,...,1.755067,1.756013,1.754996,1.752716,1.750441,1.748238,1.748696,1.751290,1.754525,1.756294
4,1.507830,1.509293,1.510683,1.511977,1.513145,1.514180,1.515125,1.516049,1.516964,1.517836,...,1.641968,1.642877,1.641946,1.639829,1.637714,1.635664,1.636101,1.638535,1.641567,1.643227

In [8]:
#collecting depedent variables in Y
Y=df['Predictor']
Y=pd.DataFrame(Y)

In [9]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
Y_encoded = Y.apply(le.fit_transform)
Y_encoded.head()

   Predictor
0         21
1         21
2         21
3         21
4         21

Pre-processing methods are helpful in eliminating noise generated by spectral data. Raw spectral data were thus processed using a combination of scatter corrections that include Standard Normal Variate (SNV) as well as first and second degree derivatives. The Savitzky-Golay and Gap-segment derivative smoothing filtering algorithms also usefull in eliminating noise.

Here I am using Savitzky-Golay filter with second degree derivative.

In [10]:
#Savitzky-Golay filter with second degree derivative.
from scipy.signal import savgol_filter 

sg=savgol_filter(X,window_length=11, polyorder=3, deriv=2, delta=1.0)

In [11]:
sg_x=pd.DataFrame(sg, columns=X_col)
sg_x.head()

,740,741,742,743,744,745,746,747,748,749,...,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070
0,0.000084,0.000073,0.000061,0.000050,0.000039,0.000028,0.000010,-0.000011,-0.000030,-0.000044,...,-0.000446,-0.000474,-0.000300,0.000008,0.000319,0.000781,0.001243,0.001705,0.002167,0.002629
1,0.000033,0.000027,0.000021,0.000014,0.000008,0.000001,-0.000011,-0.000024,-0.000036,-0.000042,...,-0.000446,-0.000474,-0.000300,0.000010,0.000322,0.000786,0.001250,0.001714,0.002178,0.002642
2,-0.000139,-0.000128,-0.000117,-0.000105,-0.000094,-0.000082,-0.000078,-0.000073,-0.000069,-0.000060,...,-0.000462,-0.000491,-0.000310,0.000010,0.000334,0.000815,0.001296,0.001777,0.002258,0.002738
3,0.000055,0.000043,0.000031,0.000020,0.000008,-0.000004,-0.000022,-0.000043,-0.000061,-0.000071,...,-0.000471,-0.000502,-0.000315,0.000014,0.000347,0.000842,0.001337,0.001832,0.002327,0.002822
4,-0.000148,-0.000133,-0.000119,-0.000105,-0.000091,-0.000077,-0.000069,-0.000062,-0.000055,-0.000045,...,-0.000446,-0.000473,-0.000299,0.000010,0.000322,0.000786,0.001249,0.001713,0.002176,0.002640

In [16]:
# Splitting the data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(sg_x, Y_encoded,
                                                    test_size=0.2,
                                                    random_state=123,stratify=Y)

In [61]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [62]:
y_pred = clf.predict(X_test)

In [63]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("Test Result:\n")        
print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, y_pred)))
print("Classification Report: \n {}\n".format(classification_report(y_test, y_pred)))
print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test,y_pred)))

Test Result:

accuracy score: 0.3000

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.00      0.00      0.00        10
           2       0.17      1.00      0.29        10
           3       0.00      0.00      0.00        10
           4       0.17      0.60      0.26        10
           5       0.00      0.00      0.00        10
           6       0.00      0.00      0.00        10
           7       0.00      0.00      0.00        10
           8       0.00      0.00      0.00        10
           9       0.00      0.00      0.00        10
          10       0.32      1.00      0.49        10
          11       0.00      0.00      0.00        10
          12       0.00      0.00      0.00        10
          13       0.50      1.00      0.67        10
          14       0.00      0.00      0.00        10
          15       0.00      0.00      0.00        10
          16       0.82      0.90      0.86        10
          17       0.00      0.00      0.00        10
          18       0.00      0.00      0.00        10
          19       0.00      0.00      0.00        10
          20       0.31      0.90      0.46        10
          21       0.26      1.00      0.41        10
          22       0.00      0.00      0.00        10
          23       0.57      0.80      0.67        10

   micro avg       0.30      0.30      0.30       240
   macro avg       0.13      0.30      0.17       240
weighted avg       0.13      0.30      0.17       240


Confusion Matrix:
 [[ 0  0  0  0  2  0  0  0  0  0  7  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0  6  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  9  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  4  0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  4  0  0  0  0  0  0  5  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  2]
 [ 0  0  0  0  6  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  7  0  0]
 [ 0  0  0  0  2  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  4  0  0]
 [ 0  0  7  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  9  0  0  0  1  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5  0  4]
 [ 0  0  5  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  9  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  9  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  0  8]]